### ISSUE TITLE
Black Diamond PD

### ISSUE THREAD

**Issue by hejokelly** [moxboxwa/wa-pursuit-pdr-data#47]
- [x] PDR sent (date - initials)
- [x]  Receipt of PDR confirmed by Joann Sloss (jsloss@blackdiamondwa.gov)
- [x]  Policy received (final installment 6/28/24)
- [x]  Policy uploaded - no data to provide.

**Comment by hejokelly** [comment]
@moxboxwa I have emailed to confirm that no data = no pursuits during the relevant time period.

**Comment by moxboxwa** [comment]
No pursuits to report
