### ISSUE TITLE
Bonney Lake PD

### ISSUE THREAD

**Issue by hejokelly** [moxboxwa/wa-pursuit-pdr-data#49]
This is a duplicate issue, since BL is in Pierce Co and their main issue #8  is under that project.

**Comment by moxboxwa** [comment]
@hejokelly and @shiraidris007 this looks like a duplicate issue for Bonney Lake, see #8 .  This issue is for AWC signatories, #8 is for the Pierce Co agencies.  

Pls check if this agency was sent multiple requests by us, thx.

**Comment by hejokelly** [comment]
@moxboxwa and @shiraidris007, the email thread is with Shira so she's in the best position to update the checklist :)
