### ISSUE TITLE
Medina PD

### ISSUE THREAD

**Issue by hejokelly** [moxboxwa/wa-pursuit-pdr-data#84]
- [x] PDR sent (6/12/24 and reopened 7/25/24 - hk)
- [x] Receipt of PDR confirmed by autoresponse: https://cityofmedinawa.nextrequest.com/requests/24-121
- [ ] Response received
- [x] ETA received (6/28/24)
- [ ] Agency requests clarification
- [ ] Data received (installment #/final)
- [ ] Data uploaded
- [ ] Harmonized file created
- [ ] Report produced

**Comment by hejokelly** [comment]
@moxboxwa from the agency (see corresondence): The Medina Police Department had no vehiclepursuits between 2019 through 2023. There are nosummaries or data to provide.

**Comment by moxboxwa** [comment]
Ok, we'll close this one out then.
